# Generated by Django 4.2.6 on 2024-04-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='last_entry_date',
            field=models.DateTimeField(null=True),
        ),
    ]
