# Generated by Django 4.2.6 on 2024-04-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Information'), ('reminder', 'Reminder'), ('points', 'Points'), ('friend', 'Friend'), ('group', 'Group')], default='info', max_length=15),
        ),
    ]
