# Generated by Django 4.2.6 on 2024-03-22 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('summary', models.TextField(max_length=1000, verbose_name='Description')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(max_length=10000, verbose_name='Entry')),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.TimeField(auto_now=True)),
                ('mood', models.CharField(choices=[('Happy', 'Happy'), ('Angry', 'Angry'), ('Neutral', 'Neutral')], max_length=7, verbose_name='Mood')),
                ('private', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Entries',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='journal_description',
            new_name='summary',
        ),
        migrations.RenameField(
            model_name='journal',
            old_name='journal_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='entry_date',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='journal_bio',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='journal_mood',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='journal_owner',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='last_edited',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='private',
        ),
    ]
