# Generated by Django 4.2.6 on 2024-03-31 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='mood',
            field=models.CharField(choices=[('Sad', 'Sad'), ('Happy', 'Happy'), ('Angry', 'Angry'), ('Neutral', 'Neutral'), ('Excited', 'Excited'), ('Confused', 'Confused'), ('Content', 'Content'), ('Surprised', 'Surprised'), ('Calm', 'Calm'), ('Hopeful', 'Hopeful'), ('Frustrated', 'Frustrated'), ('Grateful', 'Grateful'), ('Inspired', 'Inspired'), ('Relaxed', 'Relaxed'), ('Optimistic', 'Optimistic'), ('Proud', 'Proud'), ('Anxious', 'Anxious'), ('Enthusiastic', 'Enthusiastic')], max_length=20, verbose_name='Mood'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='summary',
            field=models.TextField(max_length=200, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='summary',
            field=models.TextField(max_length=350, verbose_name='Description'),
        ),
    ]
