# Generated by Django 4.2.6 on 2024-03-06 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='journal',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.group'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='journal_bio',
            field=django_ckeditor_5.fields.CKEditor5Field(max_length=10000, verbose_name='Entry'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='journal_description',
            field=models.TextField(max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='journal_mood',
            field=models.CharField(choices=[('Sad', 'Sad'), ('Happy', 'Happy'), ('Angry', 'Angry'), ('Neutral', 'Neutral')], max_length=7, verbose_name='Mood'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='journal_title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('bio', django_ckeditor_5.fields.CKEditor5Field(max_length=10000, verbose_name='Entry')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
