# Generated by Django 4.2.6 on 2024-03-29 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_usermessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionCooldown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50)),
                ('last_performed', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooldowns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'action_type')},
            },
        ),
    ]
