# Generated by Django 4.2.6 on 2024-03-27 06:12

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_journal_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nationality',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
