# Generated by Django 4.2.6 on 2024-03-07 14:44

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_friendrequest_unique_together_journal_private_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_title', models.CharField(max_length=50, verbose_name='Title')),
                ('journal_description', models.CharField(max_length=1000, verbose_name='Description')),
                ('journal_bio', django_ckeditor_5.fields.CKEditor5Field(max_length=10000, verbose_name='Entry')),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('journal_mood', models.CharField(choices=[('Sad', 'Sad'), ('Happy', 'Happy'), ('Angry', 'Angry'), ('Neutral', 'Neutral')], max_length=7, verbose_name='Mood')),
            ],
        ),
        migrations.CreateModel(
            name='GroupJournal',
            fields=[
                ('abstractjournal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='journal.abstractjournal')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.group')),
            ],
            bases=('journal.abstractjournal',),
        ),
    ]
