# Generated by Django 4.2.6 on 2024-03-22 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_entry_delete_entries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='journal.journal'),
        ),
    ]
