# Generated by Django 4.2.6 on 2024-03-31 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_entry_mood_alter_entry_summary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('summary', models.TextField(max_length=200, verbose_name='Summary')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(max_length=10000, verbose_name='Entry Content')),
                ('last_edited', models.TimeField(auto_now=True)),
                ('mood', models.CharField(choices=[('Sad', 'Sad'), ('Happy', 'Happy'), ('Angry', 'Angry'), ('Neutral', 'Neutral'), ('Excited', 'Excited'), ('Confused', 'Confused'), ('Content', 'Content'), ('Surprised', 'Surprised'), ('Calm', 'Calm'), ('Hopeful', 'Hopeful'), ('Frustrated', 'Frustrated'), ('Grateful', 'Grateful'), ('Inspired', 'Inspired'), ('Relaxed', 'Relaxed'), ('Optimistic', 'Optimistic'), ('Proud', 'Proud'), ('Anxious', 'Anxious'), ('Enthusiastic', 'Enthusiastic')], max_length=20, verbose_name='Mood')),
                ('journal_title', models.CharField(max_length=50)),
                ('journal_description', models.TextField(max_length=1000)),
                ('journal_bio', django_ckeditor_5.fields.CKEditor5Field(max_length=10000, verbose_name='Entry')),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('journal_mood', models.CharField(choices=[('Sad', 'Sad'), ('Happy', 'Happy'), ('Angry', 'Angry'), ('Neutral', 'Neutral')], max_length=7)),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.group')),
            ],
        ),
        migrations.DeleteModel(
            name='GroupJournal',
        ),
    ]
