# Generated by Django 4.2.6 on 2024-03-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='current_level',
            field=models.IntegerField(default=1),
        ),
    ]
