# Generated by Django 4.2.6 on 2024-03-26 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_level_current_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='mood',
            field=models.CharField(choices=[('Sad', 'Sad'), ('Happy', 'Happy'), ('Angry', 'Angry'), ('Neutral', 'Neutral')], max_length=7, verbose_name='Mood'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='summary',
            field=models.TextField(max_length=150, verbose_name='Summary'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='summary',
            field=models.TextField(max_length=150, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='template',
            name='description',
            field=models.TextField(max_length=150, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='template',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Title'),
        ),
    ]
